// Questions
var q = [
	// 'What do you understand that others don&#39;t?',
	// 'Why will you succeed?',
	// 'How big an opportunity is there?',
	// 'What problems/hurdles are you anticipating?',
	// 'Who would use your product?',
	// 'How much does customer acquisition cost?',
	// 'How will you make money?',
	// 'How much money could you make per year?',
	// 'How many users do you have?',
	// 'What is your user growth rate?',
	// 'How many users are paying?',
	// 'How are you meeting customers?',
	// 'How are you understanding customer needs?',
	// 'How will you get users?',
	// 'Who would you hire or how would you add to your team?',
	
	// 'So what are you working on?',
	// 'Do you have a demo?',
	// 'Where is the rocket science here?',
	// 'How does your product work in more detail?',
	// 'How is your product different?',
	// 'What are you going to do next?',
	// 'What&#39;s new about what you make?',
	// 'What, exactly, makes you different from existing options?',
	// 'Who needs what you&#39;re making?',
	// 'How do you know customers need what you&#39;re making?',
	// 'Why isn&#39;t someone already doing this?',
	// 'What obstacles will you face and how will you overcome them?',
	// 'How will customers and/or users find out about you?',
	// 'What resistance will they have to trying you and how will you overcome it?',
	// 'What are the key things about your field that outsiders don&#39;t understand?',
	// 'What part of your project are you going to build first?',
	// 'Who is going to be your first paying customer?',
	// 'If your startup succeeds, what additional areas might you be able to expand into?',
	// 'Why did you choose this idea?',
	// 'What have you learned so far from working on your product?',
	// 'Six months from now, what&#39;s going to be your biggest problem?',
	// 'Where do new users come from?',
	// 'What is your growth like?',
	// 'What&#39;s the conversion rate?',
	// 'What makes new users try you?',
	// 'Why do the reluctant users hold back?',
	// 'What are the top things users want?',
	// 'What has surprised you about user behaviour?',
	// 'What&#39;s an impressive thing you have done?',
	// 'What do you understand about your users?',
	// 'Why did you pick this idea to work on?',
	// 'What domain expertise do you have?',
	// 'Who are your competitors?',
	// 'Who might become competitors?',
	// 'Someone just showed us an idea like this right before you guys. I don&#39;t like it. What else do you have?',
	// 'What competition do you fear most?',
	// 'What is your distribution strategy?',
	// 'How did your team meet?',
	// 'Why did your team get together?',
	// 'Who in your team does what?',
	// 'Who is &quot;the boss&quot;?',
	// 'What will you do if we don&#39;t fund you?',
	// 'Would you relocate to Silicon Valley?',
	// 'How do we know your team will stick together?',
	// 'What else have you created together?',
	// 'Are you open to changing your idea? ',
	// 'What systems have you hacked?',
	// 'Tell us about a tough problem you solved?',
	// 'In what ways are you resourceful?',
	// 'Will you reincorporate as a US company?',
	// 'Will your team stick at this?',
	// 'Tell us something surprising you have done?',
	// 'What&#39;s the funniest thing that has happened to you?',
	// 'What&#39;s the worst thing that has happened?',
	// 'What&#39;s the biggest mistake you have made?',
	// 'What is your burn rate?',
	// 'How long can you go before funding?',
	// 'What is the next step with the product evolution?',
	// 'Have you raised funding?',
	// 'Who would be your next hire?',
	
	// 'How do you know people want this?',
	// 'What do you know about this space/product others don&#39;t know?'

"Why the right team to solve this problem",
"Why do we care about this problem",
"How big could this market get to",
"How do you prove the market size?",
"How do you prove the market’s willingness to pay?",
"What are you working on?",
"Who would use your product?",
"How do you know customers need what you’re making? * How do you know people want this?",
"How will you make money?",
"How much money could you make per year?",
"Why isn’t someone already doing this?",
"Why will you succeed over others? What do you understand that others don’t?",
"What have you learned so far from working on your product?",
"How much does customer acquisition cost?",
"How many users do you have?",
"Where do new users come from? How do users find out about you?",
"How are you meeting customers?",
"What is your distribution strategy? How will you grow?",
"What makes new users try you?",
"Why do the reluctant users hold back?",
"What is your growth like?",
"What is your user growth rate?",
"What’s the conversion rate?",
"How many users are paying?",
"Who is going to be your first paying customer?",
"What resistance will users have to trying you and how will you overcome it?",
"How are you understanding customer needs?",
"What are the top things your users want?",
"What has surprised you about user behavior?",
"What’s new about what you make?",
"What problems and hurdles are you anticipating?",
"How will you overcome them?",
"Six months from now, what’s going to be your biggest problem?",
"Why did you choose this idea?",
"Why did you pick this idea to work on?",
"Where is the rocket science here?",
"What do you understand about your users?",
"What domain expertise do you have?",
"What are the key things about your field that outsiders don’t understand?",
"What’s an impressive thing you have done?",
"How did your team meet?",
"Why did your team get together?",
"Who in your team does what?",
"Who would you hire or how would you add to your team? Who would be your next hire?",
"What part of your project are you going to build first?",
"What are you going to do next?",
"What is the next step with the product evolution?",
"If your startup succeeds, what additional areas might you be able to expand into?",
"Who are your competitors?",
"Who might become competitors?",
"What competition do you fear most?",
"How long can you go before funding?",
"Have you raised funding to date?",
"What will you do if we don’t fund you?",
"Would you relocate to better your business?",
"Who is &#39;the boss&#39;?",
"How do we know your team will stick together?",
"Will your team stick at this?",
"What else have you created together?",
"Are you open to changing your idea?",
"We’re not really sure this product can be huge, but we like you. What else do you have?",
"What are your passions outside of work?",
"What systems have you hacked?",
"Tell us about a tough problem you solved?",
"In what ways are you resourceful?",
"What is something surprising you have done?",
"What’s the funniest thing that has happened to you?",
"What’s the worst thing that has happened? What’s the biggest mistake you have made?",
"Tell me about DataSages.ai?",
"There is a bunch of other gungho founders here. What makes you guys different? What motivates you?",
"What do you spend most of your time doing?",
"Whats the big problem you’re solving?",
"How big is the market – how many potential customers can you have?",
"Why do you have high growth potential?",
"What is the lifetime value of a customer?",
"How long does it take to convert a trial into a paying customer?",
"How long will it take you to get them?",
"What have been the key learnings from a technology perspective?",
"Who are your competitors?",
"What are your strengths?",
"What are your legal/liability risks?",
"Do you have an exit plan?  Who are your potential acquirers?",
"What IP do you own?",
"What are the key metrics you focus on when managing the business day to day?",
"What are you planning to do with the money from any investment?",
"How do you engage your customers?",
"What key marketing point are you betting on when it comes to pricing?",
"What frameworks are your using and are you building scalable products?",
"Do you have an exit strategy?",
"What are your milestones for the coming months?",
"What’s the hardest part about the business you’re building? What have you learned since you started? And what have you learned with your first customer?",
"If this were to fail, what’s the most likely reason?”",
"If I gave you $200k in cash and said you needed to spend that money on hiring people, who would you hire?",
"Who are your (likely) customers?",
"What would be your ideal outcome from working with Betaworks?",
"What are the most important *leading* indicators for your business/product? or What’s your most important KPI this week?",
"We want to know what’s the most important unknown you need to figure out next, and also what your plan is for doing that.",
"How did you validate this market, and what is the scope of the market?",
"We want to know where you see the market going in the next few years, and if you can scale. The big question you need to answer is: can you defend this against a team that may be better funded?",
"What led you to apply to Betaworks?",
"Why are you building this company?",
"What problem are you solving?",
"Tell me about each member of your team and how they contribute to your overall success.",
"How do you know each other?",
"What’s the biggest organization (in headcount) that you could picture becoming?",
"How do you make decisions?",
"Who is the most indispensable person on the team?",
"Tell us about a conflict within the team that you’ve resolved.",
"How do you decide compensation for each other?",
"How did you decide who was the CEO?",
"How hard would it be to recover if your co-founder/CTO/etc. left tomorrow?",
"Who is your customer?",
"Who built the current product?",
"How long have you been working on this?",
"Do you have a development roadmap?",
"BizDev roadmap? How far out do they go? What are you going to accomplish in the next three months and one year?",
"What do you think the lifetime capital requirements of this company will be? How much total money will you need to raise?",
"Are you working on this full time?",
"How are you paying your bills?",
"Walk us through the competitive landscape.",
"What early assumption(s) do you feel confident about and are building around?",
"What are your ultimate expectations for this business? ",
"Big acquisition? Small acquisition? Run it forever and IPO?",
"What are you most worried about right now?",
"If you were offered $1 million for the business right now, would you take it?",
"How do you plan to take over the world?",
"What, exactly, makes you different from existing options?",
"Why did you pick this idea to work on?",
"How do you know customers need what you&#39;re making?",
"How much does customer acquisition cost?",
"How long can you go before funding?",
"What will you do if we don&#39;t fund you?",
"What problems/hurdles are you anticipating?",
"What are the key things about your field that outsiders don&#39;t understand?",
"What&#39;s an impressive thing you have done?",
"What&#39;s the funniest thing that has happened to you?",
"In what ways are you resourceful?",
"How are you meeting customers?",
"What competition do you fear most?",
"Who in your team does what?",
"Where is the rocket science here?",
"Why did your team get together?",
"How is your product different?",
"What systems have you hacked?",
"How do you know people want this?",
"Where do new users come from?",
"What do you know about this space/product others don&#39;t know?",
"How big an opportunity is there?",
"What is the next step with the product evolution?",
"What&#39;s the biggest mistake you have made?",
"What domain expertise do you have?",
"If your startup succeeds, what additional areas might you be able to expand into?",
"Are you open to changing your idea?",
"What are you going to do next?",
"What makes new users try you?",
"What is your distribution strategy?",
"Why do the reluctant users hold back?",
"How will customers and/or users find out about you?",
"How many users are paying?",
"Are your customers one-and-done, or do they come back?",
"What are other ways people solve this problem?",
"What are your numbers? (to be elaborated into more questions)",
"Why haven’t you made more progress?",
"How will you make money?",
"Why is your product priced the way it is?",
"Why do you want to be part of YC?",
"What are you going to do next?",
"How long can you go before funding?",
"Are you open to changing your idea?",
"How do you think about your ASP (average selling price) over time? Do you think this will go up, down, or stay about the same? Why?",
"What could you do to expand your TAM?",
"How big is this market, really?",
"How do you know that this isn’t just for [subculture or niche user base]?",
"What’s the worst thing that happened?",
"What’s the biggest mistake you have made?",
"What problems / hurdles are you anticipating? How will you overcome them?",
"What will be the biggest challenge two years from now?",
"Why did you pick this idea to work on?",
"Have you raised funding?",
"What’s the funniest thing that has happened to you?",
"Tell us something surprising you have done?",
"What’s an impressive thing you’ve done?",
"What systems have you hacked?",
"Will you reincorporate as a Delaware C-Corp?",
"How do you all know each other?",
"Who are the other founders? (If you have <10% ownership founders)",
"Why did your team get together?",
"How did your team meet?",
"Who in your team does what?",
"In what ways are you resourceful?",
"What is your growth like?",
"How many users do you have?",
"What is your user growth rate?",
"How many users have ever engaged?",
"What is your burn rate?",
"What’s the conversion rate?",
"What’s the repeat buyer rate?",
"What’s the churn rate?",
"How much does customer acquisition cost?",
"What is the average price of a [purchase, subscription, etc]?",
"Please quantify your market size.",
"Why is your startup the top solution for this [market] issue?",
"Can you narrowly define the problem your startup is trying to solve?",
"Who will be your first paying customer/who was your first customer?",
"In terms of user acquisition, what is your plan for overcoming resistance?",
"What’s the biggest mistake your startup has made so far?",
"Will we need to compose a business plan for you?",
"Do you have a straightforward and appropriate mission statement?",
"How will you create revenue?",
"How easy is it for your target market to find your product/service?",
"Currently, what is your top-level key performance indicator?",
"Why did your team form in the beginning?",
"What are some key aspects of your field that most people don’t know about?",
"What is likely to be your primary challenge several months from now?",
"How long is your product development cycle?",
"What are you using to find metrics of how users engage with your product/service?",
"Tell us what you are working on",
"Excluding new signups, how many users were active last week?",
"How are these active users using your product?",
"How are you different from Retool? How are you different from Notion?",
"Given that you are so close to Retool, if Retool would offer you $25m to buy you and you don’t have to build anything out, what would you do?",
"What is your ground-up calculation of the total market size?",
"What are the use cases you are seeing?",
"Notion took 3-4 years before it got popular. People take time to adopt new things. What makes you think people will use you?",
"There was a question about the competitive market. Something along the lines of how do you know people want this and are willing to pay?",
"Would you move to the US?",
"How do you split the roles between the two of you?",
"Why start a company?",
"When did you start building the product? How long did it take?",
];

// Tips
var tips = [
	'Try to have quick and concise answers.',
	'Try to answer in 2 to 3 sentences.',
	'Answer like you would in a conversation, this is not a presentation.',
	'When talking to PG and the other YC partners, be substantive, and get straight to the point.',
	'DO NOT BEAT AROUND THE BUSH. Do not hem and haw. "Uhm"s and "uh"s don&#39;t lend an aura of intelligence.',
	'Use precise and concise language. You aren&#39;t pitching a VC that will ask you what your "secret sauce" is.',
	'He talks quickly, and so do the other YC partners. Try to match their tempo (as you should when talking to anyone).'
];